require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1.2
  NewCops: enable
  Exclude:
    - 'bin/**'
    - 'db/migrate/**'
    - 'config/**/*'
    - 'db/schema.rb'

Layout/LineLength:
  Max: 100

Layout/MultilineMethodCallIndentation:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 15

Rails/I18nLocaleTexts:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Style/Documentation:
  Enabled: false
