require: rubocop-rails

AllCops:
  TargetRubyVersion: 3.1.2
  NewCops: enable
  Exclude:
    - 'bin/**'
    - 'db/migrate/**'
    - 'config/**/*'
    - 'db/schema.rb'

Style/Documentation:
  Enabled: false
