require: rubocop-rails

AllCops:
  TargetRubyVersion: 3.1.2
  NewCops: enable
  Exclude:
    - 'bin/**'
    - 'db/migrate/**'
    - 'config/**/*'
    - 'db/schema.rb'

Layout/LineLength:
  Max: 100

Layout/MultilineMethodCallIndentation:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Max: 15

Rails/DeprecatedActiveModelErrorsMethods:
  Exclude:
    - 'spec/contracts/*.rb'

Rails/I18nLocaleTexts:
  Enabled: false

Style/Documentation:
  Enabled: false
